version: "3.1"
services:
  db:
    image: mysql:latest
    container_name: catalog-db
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=catalog
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=test
    ports:
      - 30006:3306

  web:
    image: nginx:alpine
    container_name: catalog-ws
    working_dir: /application
    volumes:
      - ./application:/application
      - ./docker/nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./docker/nginx/backend.conf:/etc/nginx/conf.d/default.conf
      - ./application/runtime/nginx:/var/log/nginx
    ports:
      - 8081:80

  php-fpm:
    build: docker/php-fpm
    container_name: catalog-php-fpm
    working_dir: /application
    volumes:
      - ./application:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/cli/conf.d/99-overrides.ini
